# Generated by Django 2.0.7 on 2018-08-04 11:56

import cpsys.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRecord',
            fields=[
                ('member_id', models.PositiveSmallIntegerField(default=cpsys.models.default_id, help_text="Member's ID", primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='ID')),
                ('first_name', models.CharField(help_text="Member's First Name", max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('last_name', models.CharField(help_text="Member's Last Name", max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('booking', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Total Points In The Booking Category', verbose_name='Booking Category')),
                ('cooking', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Total Points In The Cooking Category', verbose_name='Cooking Category')),
                ('general', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Total Points In The General Activity Category', verbose_name='General Activity Category')),
                ('negative', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Total Deductable Points', verbose_name='Negative Points')),
                ('date_added', models.DateTimeField(auto_now=True, help_text="When Was Member's Record Added?")),
            ],
            options={
                'verbose_name_plural': 'Member Records',
                'db_table': 'member_records',
                'ordering': ['member_id', 'first_name', 'last_name'],
            },
        ),
    ]
