# Generated by Django 2.0.7 on 2018-08-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teamrecord',
            table=None,
        ),
    ]
