# Generated by Django 2.0.7 on 2018-08-04 13:14

import cpsys.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0002_auto_20180804_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.PositiveSmallIntegerField(default=cpsys.models.default_id, help_text="Member's ID", primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='ID')),
                ('first_name', models.CharField(help_text="Member's First Name", max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('last_name', models.CharField(help_text="Member's Last Name", max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('member_age', models.PositiveSmallIntegerField(help_text="Member's Age", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Age')),
                ('phone_number', models.CharField(help_text="Member's Phone Number", max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('national_id', models.IntegerField(help_text='National ID/Passport Number', unique=True, validators=[django.core.validators.MinValueValidator(11111111), django.core.validators.MaxValueValidator(99999999)])),
                ('type_of_member', models.CharField(choices=[('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior Consultant', 'Senior Consultant'), ('Distributor', 'Distributor'), ('Dealer', 'Dealer')], help_text="Member's rank", max_length=50)),
                ('contract_signed', models.BooleanField(help_text='Contract status', verbose_name='Contract Status')),
            ],
        ),
        migrations.AlterModelOptions(
            name='teamrecord',
            options={'verbose_name_plural': 'Member Points'},
        ),
        migrations.RemoveField(
            model_name='teamrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teamrecord',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teamrecord',
            name='member_id',
        ),
        migrations.AddField(
            model_name='teamrecord',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamrecord',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cpsys.Member', unique=True),
            preserve_default=False,
        ),
    ]
