# Generated by Django 2.0.7 on 2018-08-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0003_auto_20180804_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpsys.Member', unique=True, verbose_name='Member Name'),
        ),
    ]
