# Generated by Django 2.0.7 on 2018-08-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0006_auto_20180804_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setsold',
            options={'ordering': ['set_sold', 'sold_by', 'date_sold'], 'verbose_name_plural': 'Sets Sold'},
        ),
        migrations.AlterField(
            model_name='setsold',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpsys.Member', verbose_name='Set Sold By'),
        ),
    ]
