# Generated by Django 2.0.7 on 2018-08-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0008_auto_20180804_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setsold',
            options={'ordering': ['set_sold', 'seller', 'date_sold'], 'verbose_name_plural': 'Sets Sold'},
        ),
        migrations.RemoveField(
            model_name='setsold',
            name='set_sold_by',
        ),
        migrations.AddField(
            model_name='setsold',
            name='seller',
            field=models.ForeignKey(default=None, help_text='Set Sold By', on_delete=django.db.models.deletion.CASCADE, to='cpsys.Member', verbose_name='Set Sold By'),
            preserve_default=False,
        ),
    ]
