# Generated by Django 2.0.7 on 2018-08-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0009_auto_20180804_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsold',
            name='seller',
            field=models.ForeignKey(default=None, help_text='Set Sold By', on_delete=django.db.models.deletion.CASCADE, to='cpsys.Member', verbose_name='Set Sold By'),
        ),
    ]
