# Generated by Django 2.0.7 on 2018-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0010_auto_20180804_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
