# Generated by Django 2.0.7 on 2018-08-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0012_auto_20180805_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Name of email receiver', max_length=30, verbose_name='Mail to')),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='to_export',
        ),
    ]
