# Generated by Django 2.0.7 on 2018-08-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0013_auto_20180805_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name_plural': 'Mailing List'},
        ),
    ]
