# Generated by Django 2.0.7 on 2018-08-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0015_auto_20180806_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.PositiveSmallIntegerField(default=0, verbose_name='B')),
                ('cooking', models.PositiveSmallIntegerField(default=0, verbose_name='C')),
                ('sets', models.PositiveSmallIntegerField(default=0, verbose_name='S')),
                ('dinner', models.PositiveSmallIntegerField(default=0, verbose_name='D')),
                ('recruited', models.PositiveSmallIntegerField(default=0, verbose_name='RE')),
                ('CA', models.PositiveSmallIntegerField(default=0, verbose_name='CA')),
            ],
            options={
                'verbose_name_plural': 'Sheets',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('Bontavita', 'Bontavita'), ('Red Vortex', 'Red Vortex'), ('Eat Well', 'Eat Well'), ('Food Matters', 'Food Matters'), ('Warriors', 'Warriors'), ('HealthLine', 'HealthLine'), ('Gold', 'Gold'), ('Avator', 'Avator'), ('LCL', 'LCL'), ('Mezani', 'Mezani'), ('Red 5', 'Red 5'), ('Nourish Tanzania', 'Nourish Tanzania'), ('Joash Investment', 'Joash Investment')], default=None, help_text='What team do you belong to?', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputsheet',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpsys.Member', verbose_name='Member'),
        ),
    ]
