# Generated by Django 2.0.7 on 2018-08-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpsys', '0016_auto_20180811_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputsheet',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Sheets'},
        ),
    ]
